### ISSUE TITLE
EC2 Instance disk size is not sufficient - to install xcode

### ISSUE THREAD

**Issue by maishsk** [aws-samples/mac1-eks-jenkins#4]
The ec2 instance that is created - is 30GB in size - when trying to install xcode on the instance - there is not enough space on the drive

**Comment by pauljrob** [comment]
Take a look at: https://github.com/aws-samples/mac1-eks-jenkins/commit/86bf79dad1e6d0501a6909d3265e5ec66047d2c0.

I set it for 60GB for now, LMK if that works for you and I'll merge.

**Comment by pauljrob** [comment]
Merged.
